apiVersion: v1
kind: Secret
metadata:
  name: sensorhub-secret
  namespace: sensorhub
type: Opaque
# stringData acepta texto plano; Kubernetes lo codifica en base64 internamente
stringData:
  MONGO_ROOT_PASSWORD: "changeme"
  MONGO_USERNAME: "root"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "changeme"
